language: r
sudo: false
cache: packages

r_packages:
  - covr
  - drat
  - mailR
  - ReporteRs

r_github_packages:
  - OHDSI/DatabaseConnector
  - OHDSI/FeatureExtraction
  - OHDSI/Cyclops
  - OHDSI/CohortMethod
  - OHDSI/PatientLevelPrediction
  - OHDSI/OhdsiRTools
  - OHDSI/OhdsiSharing
  - OHDSI/SqlRender

before_script:
  - export PKG_NAME_NS=$(Rscript -e 'cat(paste0(devtools::as.package("./NoacStudy")$package))')
  - export PKG_TARBALL_NS=$(Rscript -e 'pkg <- devtools::as.package("./NoacStudy"); cat(paste0(pkg$package,"_",pkg$version,".tar.gz"))')


# Build and check NoacStudy package
script:
  - R CMD build NoacStudy --no-build-vignettes --no-manual
  - _R_CHECK_CRAN_INCOMING_=FALSE R CMD check "${PKG_TARBALL_NS}" --no-build-vignettes --no-manual
  - cat ${PKG_NAME_NS}.Rcheck/00install.out # Print out install / compile log

notifications:
  recipients:
    - msuchard@gmail.com
    - schuemie@ohdsi.org
  email:
    on_success: change
    on_failure: change

after_success:
  # Deploy to drat repo
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash deploy.sh
